#!/usr/bin/env bash

# don't let ssh forward our italics TERM to machines that don't have
# our custom TERM
alias ssh='TERM=xterm-256color ssh'

alias ..='cd ..'

alias ls='ls'
alias ll='ls -ahl'

### system
# IP addresses
function ips() {
  echo "Public: $(dig +short myip.opendns.com @resolver1.opendns.com)"
  echo "Local: $(ipconfig getifaddr en0)"

  if [[ $OSTYPE == darwin* ]]; then
    echo "Gateway: $(route -n get default | awk '/gateway/ {print $2}')"
  fi
}
alias ips='ips'

### OSX
if [[ $OSTYPE == darwin* ]]; then
  alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup'
  alias flushdns='sudo killall -HUP mDNSResponder'

  # Hide/show all desktop icons (useful when presenting)
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
fi
