#!/usr/bin/env bash

# Only display up to four directory components in the prompt.
PROMPT_DIRTRIM=4

# prompt colors
BLACK="\[$(tput setaf 0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
YELLOW="\[$(tput setaf 3)\]"
BLUE="\[$(tput setaf 4)\]"
MAGENTA="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
WHITE="\[$(tput setaf 7)\]"
BLACKLIGHT="\[$(tput setaf 8)\]"
LIGHTRED="\[$(tput setaf 9)\]"
LIGHTGREEN="\[$(tput setaf 10)\]"
LIGHTORANGE="\[$(tput setaf 11)\]"
LIGHTBLUE="\[$(tput setaf 12)\]"
LIGHTMAGENTA="\[$(tput setaf 13)\]"
LIGHTCYAN="\[$(tput setaf 14)\]"
LIGHTWHITE="\[$(tput setaf 15)\]"
RESET="\[$(tput sgr0)\]"

function git_prompt() {
  branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
  if [[ $? == 0 ]]; then
    printf "(%.10s%s) " "$branch" "$([[ -n $(git status -s) ]] && echo " ✗")"
  fi
}

function status_symbol() {
  if [[ $1 != 0 ]]; then
    echo -n "⚡ $1 ⚡ "
  fi
}

function right_prompt() {
  local str="$(date +'%H:%M:%S')"

  if [[ "$SSH_TTY" ]]; then
    str="$(id -u -n)@$(hostname -s) $str"
  fi

  tput sc
  printf "%*s" $COLUMNS "$str"
  tput rc
}

PS1="$LIGHTBLUE\$(LS=\$?; right_prompt; exit \$LS)"
PS1+="$RED\$(status_symbol \$?)$RESET\n"
if [[ "$(id -u)" == 0 ]]; then
  PS1+="${ORANGE}root"
else
  PS1+="\u"
fi
PS1+="$RESET@$BLUE\h:$RESET\w \$(git_prompt)"
PS1+="$GREEN\\$ $RESET"

export PS1
